package mx.com.televisa.landamark.model.list;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 18 20:38:42 CDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntListChannelpAllVwViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_LMKINTLISTCHANNELPALLVW = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RowId1,
        IdService,
        NomService,
        IndDescService,
        IdParameter,
        NomParameter,
        IndDescParameter,
        IndUsedBy,
        IndValueParameter,
        IndEstatus,
        FecCreationDate,
        ValMostrar,
        ValValue,
        Selected;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROWID1 = AttributesEnum.RowId1.index();
    public static final int IDSERVICE = AttributesEnum.IdService.index();
    public static final int NOMSERVICE = AttributesEnum.NomService.index();
    public static final int INDDESCSERVICE = AttributesEnum.IndDescService.index();
    public static final int IDPARAMETER = AttributesEnum.IdParameter.index();
    public static final int NOMPARAMETER = AttributesEnum.NomParameter.index();
    public static final int INDDESCPARAMETER = AttributesEnum.IndDescParameter.index();
    public static final int INDUSEDBY = AttributesEnum.IndUsedBy.index();
    public static final int INDVALUEPARAMETER = AttributesEnum.IndValueParameter.index();
    public static final int INDESTATUS = AttributesEnum.IndEstatus.index();
    public static final int FECCREATIONDATE = AttributesEnum.FecCreationDate.index();
    public static final int VALMOSTRAR = AttributesEnum.ValMostrar.index();
    public static final int VALVALUE = AttributesEnum.ValValue.index();
    public static final int SELECTED = AttributesEnum.Selected.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntListChannelpAllVwViewRowImpl() {
    }

    /**
     * Gets LmkIntListChannelpAllVw entity object.
     * @return the LmkIntListChannelpAllVw
     */
    public EntityImpl getLmkIntListChannelpAllVw() {
        return (EntityImpl) getEntity(ENTITY_LMKINTLISTCHANNELPALLVW);
    }

    /**
     * Gets the attribute value for ROW_ID using the alias name RowId1.
     * @return the ROW_ID
     */
    public Float getRowId1() {
        return (Float) getAttributeInternal(ROWID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ROW_ID using the alias name RowId1.
     * @param value value to set the ROW_ID
     */
    public void setRowId1(Float value) {
        setAttributeInternal(ROWID1, value);
    }

    /**
     * Gets the attribute value for ID_SERVICE using the alias name IdService.
     * @return the ID_SERVICE
     */
    public Integer getIdService() {
        return (Integer) getAttributeInternal(IDSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SERVICE using the alias name IdService.
     * @param value value to set the ID_SERVICE
     */
    public void setIdService(Integer value) {
        setAttributeInternal(IDSERVICE, value);
    }

    /**
     * Gets the attribute value for NOM_SERVICE using the alias name NomService.
     * @return the NOM_SERVICE
     */
    public String getNomService() {
        return (String) getAttributeInternal(NOMSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for NOM_SERVICE using the alias name NomService.
     * @param value value to set the NOM_SERVICE
     */
    public void setNomService(String value) {
        setAttributeInternal(NOMSERVICE, value);
    }

    /**
     * Gets the attribute value for IND_DESC_SERVICE using the alias name IndDescService.
     * @return the IND_DESC_SERVICE
     */
    public String getIndDescService() {
        return (String) getAttributeInternal(INDDESCSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_DESC_SERVICE using the alias name IndDescService.
     * @param value value to set the IND_DESC_SERVICE
     */
    public void setIndDescService(String value) {
        setAttributeInternal(INDDESCSERVICE, value);
    }

    /**
     * Gets the attribute value for ID_PARAMETER using the alias name IdParameter.
     * @return the ID_PARAMETER
     */
    public Integer getIdParameter() {
        return (Integer) getAttributeInternal(IDPARAMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_PARAMETER using the alias name IdParameter.
     * @param value value to set the ID_PARAMETER
     */
    public void setIdParameter(Integer value) {
        setAttributeInternal(IDPARAMETER, value);
    }

    /**
     * Gets the attribute value for NOM_PARAMETER using the alias name NomParameter.
     * @return the NOM_PARAMETER
     */
    public String getNomParameter() {
        return (String) getAttributeInternal(NOMPARAMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for NOM_PARAMETER using the alias name NomParameter.
     * @param value value to set the NOM_PARAMETER
     */
    public void setNomParameter(String value) {
        setAttributeInternal(NOMPARAMETER, value);
    }

    /**
     * Gets the attribute value for IND_DESC_PARAMETER using the alias name IndDescParameter.
     * @return the IND_DESC_PARAMETER
     */
    public String getIndDescParameter() {
        return (String) getAttributeInternal(INDDESCPARAMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_DESC_PARAMETER using the alias name IndDescParameter.
     * @param value value to set the IND_DESC_PARAMETER
     */
    public void setIndDescParameter(String value) {
        setAttributeInternal(INDDESCPARAMETER, value);
    }

    /**
     * Gets the attribute value for IND_USED_BY using the alias name IndUsedBy.
     * @return the IND_USED_BY
     */
    public String getIndUsedBy() {
        return (String) getAttributeInternal(INDUSEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_USED_BY using the alias name IndUsedBy.
     * @param value value to set the IND_USED_BY
     */
    public void setIndUsedBy(String value) {
        setAttributeInternal(INDUSEDBY, value);
    }

    /**
     * Gets the attribute value for IND_VALUE_PARAMETER using the alias name IndValueParameter.
     * @return the IND_VALUE_PARAMETER
     */
    public String getIndValueParameter() {
        return (String) getAttributeInternal(INDVALUEPARAMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_VALUE_PARAMETER using the alias name IndValueParameter.
     * @param value value to set the IND_VALUE_PARAMETER
     */
    public void setIndValueParameter(String value) {
        setAttributeInternal(INDVALUEPARAMETER, value);
    }

    /**
     * Gets the attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @return the IND_ESTATUS
     */
    public String getIndEstatus() {
        return (String) getAttributeInternal(INDESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @param value value to set the IND_ESTATUS
     */
    public void setIndEstatus(String value) {
        setAttributeInternal(INDESTATUS, value);
    }

    /**
     * Gets the attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @return the FEC_CREATION_DATE
     */
    public Timestamp getFecCreationDate() {
        return (Timestamp) getAttributeInternal(FECCREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @param value value to set the FEC_CREATION_DATE
     */
    public void setFecCreationDate(Timestamp value) {
        setAttributeInternal(FECCREATIONDATE, value);
    }

    /**
     * Gets the attribute value for VAL_MOSTRAR using the alias name ValMostrar.
     * @return the VAL_MOSTRAR
     */
    public String getValMostrar() {
        return (String) getAttributeInternal(VALMOSTRAR);
    }

    /**
     * Sets <code>value</code> as attribute value for VAL_MOSTRAR using the alias name ValMostrar.
     * @param value value to set the VAL_MOSTRAR
     */
    public void setValMostrar(String value) {
        setAttributeInternal(VALMOSTRAR, value);
    }

    /**
     * Gets the attribute value for VAL_VALUE using the alias name ValValue.
     * @return the VAL_VALUE
     */
    public String getValValue() {
        return (String) getAttributeInternal(VALVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for VAL_VALUE using the alias name ValValue.
     * @param value value to set the VAL_VALUE
     */
    public void setValValue(String value) {
        setAttributeInternal(VALVALUE, value);
    }

    /**
     * Gets the attribute value for SELECTED using the alias name Selected.
     * @return the SELECTED
     */
    public String getSelected() {
        return (String) getAttributeInternal(SELECTED);
    }

    /**
     * Sets <code>value</code> as attribute value for SELECTED using the alias name Selected.
     * @param value value to set the SELECTED
     */
    public void setSelected(String value) {
        setAttributeInternal(SELECTED, value);
    }
}

