package mx.com.televisa.landamark.client.pricest;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1047
public class SpotConciliacionWSPortClient {
    public static void main(String[] args) {
        SpotConciliacionWSService spotConciliacionWSService = new SpotConciliacionWSService();
        SpotConciliacionWS spotConciliacionWS = spotConciliacionWSService.getSpotConciliacionWSPort();
        // Add your code to call the desired methods.


    }
}
