
package mx.com.televisa.landamark.client.pricest;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.landamark.util.UtilFaces;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
/*@WebServiceClient(name = "SpotConciliacionWSService", targetNamespace = "http://impl.webservice.rtcrd.televisa.com.mx/",
                  wsdlLocation =
                  "http://tvel01cn03.televisa.net:19401/RTCRDApp/SpotConciliacionWSService?WSDL#%7Bhttp%3A%2F%2Fimpl.webservice.rtcrd.televisa.com.mx%2F%7DSpotConciliacionWSService")*/
@WebServiceClient(name = "SpotConciliacionWSService", targetNamespace = "http://impl.webservice.rtcrd.televisa.com.mx/")
public class SpotConciliacionWSService extends Service {

    private final static URL SPOTCONCILIACIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPOTCONCILIACIONWSSERVICE_EXCEPTION;
    private final static QName SPOTCONCILIACIONWSSERVICE_QNAME =
        new QName("http://impl.webservice.rtcrd.televisa.com.mx/", "SpotConciliacionWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String lsDynaUrl = new UtilFaces().getConfigParameterByName("WsSpotConciliacionService");
            url = new URL(lsDynaUrl);
            //url =
              //  new URL("http://tvel01cn03.televisa.net:19401/RTCRDApp/SpotConciliacionWSService?WSDL#%7Bhttp%3A%2F%2Fimpl.webservice.rtcrd.televisa.com.mx%2F%7DSpotConciliacionWSService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPOTCONCILIACIONWSSERVICE_WSDL_LOCATION = url;
        SPOTCONCILIACIONWSSERVICE_EXCEPTION = e;
    }

    public SpotConciliacionWSService() {
        super(__getWsdlLocation(), SPOTCONCILIACIONWSSERVICE_QNAME);
    }

    public SpotConciliacionWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPOTCONCILIACIONWSSERVICE_QNAME, features);
    }

    public SpotConciliacionWSService(URL wsdlLocation) {
        super(wsdlLocation, SPOTCONCILIACIONWSSERVICE_QNAME);
    }

    public SpotConciliacionWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPOTCONCILIACIONWSSERVICE_QNAME, features);
    }

    public SpotConciliacionWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpotConciliacionWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SpotConciliacionWS
     */
    @WebEndpoint(name = "SpotConciliacionWSPort")
    public SpotConciliacionWS getSpotConciliacionWSPort() {
        return super.getPort(new QName("http://impl.webservice.rtcrd.televisa.com.mx/", "SpotConciliacionWSPort"),
                             SpotConciliacionWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpotConciliacionWS
     */
    @WebEndpoint(name = "SpotConciliacionWSPort")
    public SpotConciliacionWS getSpotConciliacionWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.rtcrd.televisa.com.mx/", "SpotConciliacionWSPort"),
                             SpotConciliacionWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPOTCONCILIACIONWSSERVICE_EXCEPTION != null) {
            throw SPOTCONCILIACIONWSSERVICE_EXCEPTION;
        }
        return SPOTCONCILIACIONWSSERVICE_WSDL_LOCATION;
    }

}
