
package mx.com.televisa.landamark.client.pricest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.televisa.landamark.client.pricest.types.ComercialListRequest;
import mx.com.televisa.landamark.client.pricest.types.ObjectFactory;
import mx.com.televisa.landamark.client.pricest.types.SpotConciliacionResponse;
import mx.com.televisa.landamark.client.pricest.types.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SpotConciliacionWS", targetNamespace = "http://impl.webservice.rtcrd.televisa.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SpotConciliacionWS {


    /**
     *
     * @param request
     * @param user
     * @return
     *     returns mx.com.televisa.landamark.client.pricest.types.SpotConciliacionResponse
     */
    @WebMethod
    @WebResult(name = "SpotConciliacionResult", targetNamespace = "")
    @RequestWrapper(localName = "spotConciliaion", targetNamespace = "http://impl.webservice.rtcrd.televisa.com.mx/",
                    className = "mx.com.televisa.landamark.client.pricest.types.SpotConciliaion")
    @ResponseWrapper(localName = "spotConciliaionResponse",
                     targetNamespace = "http://impl.webservice.rtcrd.televisa.com.mx/",
                     className = "mx.com.televisa.landamark.client.pricest.types.SpotConciliaionResponse")
    @Action(input = "http://impl.webservice.rtcrd.televisa.com.mx/SpotConciliacionWS/spotConciliaionRequest",
            output = "http://impl.webservice.rtcrd.televisa.com.mx/SpotConciliacionWS/spotConciliaionResponse")
    public SpotConciliacionResponse spotConciliaion(@WebParam(name = "Request", targetNamespace = "")
                                                    ComercialListRequest request,
                                                    @WebParam(name = "User", targetNamespace = "") User user);

}
