
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfBookProcessType;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfCopySelectionName;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfInteractivite;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfPositionInProgrammeName;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpot;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpotListReportType;
import org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpotStatusIncludingActive;
import org.datacontract.schemas._2004._07.landmark_classes.BookingResults;
import org.datacontract.schemas._2004._07.landmark_parameters.BatchBookingParams;
import org.datacontract.schemas._2004._07.landmark_parameters.SpotListFilter;
import org.datacontract.schemas._2004._07.landmark_parameters.SpotSequenceMaintain;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ILandmarkSpotsSpot", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
            com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
            com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
            org.datacontract.schemas._2004._07.landmark_classes.ObjectFactory.class,
            org.datacontract.schemas._2004._07.landmark_parameters.ObjectFactory.class, org.tempuri.ObjectFactory.class
    })
public interface ILandmarkSpotsSpot {


    /**
     *
     * @param spotListFilter
     * @param currency
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpot
     */
    @WebMethod(operationName = "LoadForFilter", action = "http://tempuri.org/ILandmarkSpotsSpot/LoadForFilter")
    @WebResult(name = "LoadForFilterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadForFilter", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadForFilter")
    @ResponseWrapper(localName = "LoadForFilterResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadForFilterResponse")
    public ArrayOfSpot loadForFilter(@WebParam(name = "spotListFilter", targetNamespace = "http://tempuri.org/")
                                     SpotListFilter spotListFilter,
                                     @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
                                     String currency);

    /**
     *
     * @param spotListFilter
     * @param currency
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpot
     */
    @WebMethod(operationName = "LoadForFilter2", action = "http://tempuri.org/ILandmarkSpotsSpot/LoadForFilter2")
    @WebResult(name = "LoadForFilter2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadForFilter2", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadForFilter2")
    @ResponseWrapper(localName = "LoadForFilter2Response", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadForFilter2Response")
    public ArrayOfSpot loadForFilter2(@WebParam(name = "spotListFilter", targetNamespace = "http://tempuri.org/")
                                      SpotListFilter spotListFilter,
                                      @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
                                      String currency);

    /**
     *
     * @param batchBookings
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.BookingResults
     */
    @WebMethod(operationName = "BatchBookings", action = "http://tempuri.org/ILandmarkSpotsSpot/BatchBookings")
    @WebResult(name = "BatchBookingsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchBookings", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.BatchBookings")
    @ResponseWrapper(localName = "BatchBookingsResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.BatchBookingsResponse")
    public BookingResults batchBookings(@WebParam(name = "batchBookings", targetNamespace = "http://tempuri.org/")
                                        BatchBookingParams batchBookings);

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpotListReportType
     */
    @WebMethod(operationName = "LoadSpotListReportTypes",
               action = "http://tempuri.org/ILandmarkSpotsSpot/LoadSpotListReportTypes")
    @WebResult(name = "LoadSpotListReportTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadSpotListReportTypes", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadSpotListReportTypes")
    @ResponseWrapper(localName = "LoadSpotListReportTypesResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadSpotListReportTypesResponse")
    public ArrayOfSpotListReportType loadSpotListReportTypes();

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfCopySelectionName
     */
    @WebMethod(operationName = "LoadCopySelection", action = "http://tempuri.org/ILandmarkSpotsSpot/LoadCopySelection")
    @WebResult(name = "LoadCopySelectionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadCopySelection", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadCopySelection")
    @ResponseWrapper(localName = "LoadCopySelectionResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadCopySelectionResponse")
    public ArrayOfCopySelectionName loadCopySelection();

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfSpotStatusIncludingActive
     */
    @WebMethod(operationName = "LoadSpotStatusIncActive",
               action = "http://tempuri.org/ILandmarkSpotsSpot/LoadSpotStatusIncActive")
    @WebResult(name = "LoadSpotStatusIncActiveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadSpotStatusIncActive", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadSpotStatusIncActive")
    @ResponseWrapper(localName = "LoadSpotStatusIncActiveResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadSpotStatusIncActiveResponse")
    public ArrayOfSpotStatusIncludingActive loadSpotStatusIncActive();

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfPositionInProgrammeName
     */
    @WebMethod(operationName = "LoadPositionInProgramme",
               action = "http://tempuri.org/ILandmarkSpotsSpot/LoadPositionInProgramme")
    @WebResult(name = "LoadPositionInProgrammeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadPositionInProgramme", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadPositionInProgramme")
    @ResponseWrapper(localName = "LoadPositionInProgrammeResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadPositionInProgrammeResponse")
    public ArrayOfPositionInProgrammeName loadPositionInProgramme();

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfInteractivite
     */
    @WebMethod(operationName = "LoadInteractivity", action = "http://tempuri.org/ILandmarkSpotsSpot/LoadInteractivity")
    @WebResult(name = "LoadInteractivityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadInteractivity", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadInteractivity")
    @ResponseWrapper(localName = "LoadInteractivityResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadInteractivityResponse")
    public ArrayOfInteractivite loadInteractivity();

    /**
     *
     * @return
     *     returns org.datacontract.schemas._2004._07.landmark_classes.ArrayOfBookProcessType
     */
    @WebMethod(operationName = "LoadBookProcessTypes",
               action = "http://tempuri.org/ILandmarkSpotsSpot/LoadBookProcessTypes")
    @WebResult(name = "LoadBookProcessTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadBookProcessTypes", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.LoadBookProcessTypes")
    @ResponseWrapper(localName = "LoadBookProcessTypesResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.LoadBookProcessTypesResponse")
    public ArrayOfBookProcessType loadBookProcessTypes();

    /**
     *
     * @param positionCode
     * @param spotSequenceMaintain
     * @param organisationCode
     */
    @WebMethod(operationName = "SaveSpotsForBreakSequence",
               action = "http://tempuri.org/ILandmarkSpotsSpot/SaveSpotsForBreakSequence")
    @RequestWrapper(localName = "SaveSpotsForBreakSequence", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.SaveSpotsForBreakSequence")
    @ResponseWrapper(localName = "SaveSpotsForBreakSequenceResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.SaveSpotsForBreakSequenceResponse")
    public void saveSpotsForBreakSequence(@WebParam(name = "spotSequenceMaintain",
                                                    targetNamespace = "http://tempuri.org/")
                                          SpotSequenceMaintain spotSequenceMaintain,
                                          @WebParam(name = "organisationCode", targetNamespace = "http://tempuri.org/")
                                          String organisationCode,
                                          @WebParam(name = "positionCode", targetNamespace = "http://tempuri.org/")
                                          String positionCode);

}
