
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.landamark.model.daos.EntityMappedDao;
import mx.com.televisa.landamark.util.UtilFaces;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
/*@WebServiceClient(name = "LandmarkSpotsSpot", targetNamespace = "http://tempuri.org/",
                  wsdlLocation =
                  "http://corpklhlatap2t.corp.televisa.com.mx:91/LandmarkSpotsSpot.svc?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DLandmarkSpotsSpot")*/
@WebServiceClient(name = "LandmarkSpotsSpot", targetNamespace = "http://tempuri.org/")
public class LandmarkSpotsSpot extends Service {

    private final static URL LANDMARKSPOTSSPOT_WSDL_LOCATION;
    private final static WebServiceException LANDMARKSPOTSSPOT_EXCEPTION;
    private final static QName LANDMARKSPOTSSPOT_QNAME = new QName("http://tempuri.org/", "LandmarkSpotsSpot");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            EntityMappedDao loEntityMappedDao = new EntityMappedDao();
            String lsDynaUrl = loEntityMappedDao.getGeneralParameter("WsLandmarkSpotService", "WS_LANDMARK");
            url = new URL(lsDynaUrl);
            //url =
              //  new URL("http://corpklhlatap2t.corp.televisa.com.mx:91/LandmarkSpotsSpot.svc?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DLandmarkSpotsSpot");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LANDMARKSPOTSSPOT_WSDL_LOCATION = url;
        LANDMARKSPOTSSPOT_EXCEPTION = e;
    }

    public LandmarkSpotsSpot() {
        super(__getWsdlLocation(), LANDMARKSPOTSSPOT_QNAME);
    }

    public LandmarkSpotsSpot(WebServiceFeature... features) {
        super(__getWsdlLocation(), LANDMARKSPOTSSPOT_QNAME, features);
    }

    public LandmarkSpotsSpot(URL wsdlLocation) {
        super(wsdlLocation, LANDMARKSPOTSSPOT_QNAME);
    }

    public LandmarkSpotsSpot(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LANDMARKSPOTSSPOT_QNAME, features);
    }

    public LandmarkSpotsSpot(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LandmarkSpotsSpot(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ILandmarkSpotsSpot
     */
    @WebEndpoint(name = "BasicHttpBinding_ILandmarkSpotsSpot")
    public ILandmarkSpotsSpot getBasicHttpBindingILandmarkSpotsSpot() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILandmarkSpotsSpot"),
                             ILandmarkSpotsSpot.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILandmarkSpotsSpot
     */
    @WebEndpoint(name = "BasicHttpBinding_ILandmarkSpotsSpot")
    public ILandmarkSpotsSpot getBasicHttpBindingILandmarkSpotsSpot(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILandmarkSpotsSpot"),
                             ILandmarkSpotsSpot.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LANDMARKSPOTSSPOT_EXCEPTION != null) {
            throw LANDMARKSPOTSSPOT_EXCEPTION;
        }
        return LANDMARKSPOTSSPOT_WSDL_LOCATION;
    }

}
