package mx.com.televisa.landamark.client.grupos;

import mx.com.televisa.landamark.client.grupos.types.UsuariosCollection;
import mx.com.televisa.landamark.client.grupos.types.UsuariosGrupoInputParameters;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1047
public class SecmanDasUsuariosGrupoPortClient {
    public static void main(String[] args) {
        SecmanDasUsuariosGrupoService secmanDasUsuariosGrupoService = new SecmanDasUsuariosGrupoService();
        SecmanDasUsuariosGrupo secmanDasUsuariosGrupo = secmanDasUsuariosGrupoService.getSecmanDasUsuariosGrupoPort();
        // Add your code to call the desired methods.
        UsuariosGrupoInputParameters loUgp = new UsuariosGrupoInputParameters();
        loUgp.setNomGrupo("IntLmkGpoLandmark");
        UsuariosCollection loUsrCol = 
        secmanDasUsuariosGrupo.obtenerUsuariosGrupo(loUgp);
        loUsrCol.getUsuarios().size();


    }
}
