package mx.com.televisa.landamark.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 18 19:44:08 CDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntServicesLogUsrpVwViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntServicesLogUsrpVwViewImpl() {
    }
    
    @Override
    protected void executeQueryForCollection(Object toQc, 
                                             Object[] taParams, 
                                             int tiNumUserParams) {
        
        String lsWhere = " 1 = 1 ";
        if(getWhereClause() == null){
            AppModuleImpl loAm = new AppModuleImpl();
            String              lsUserName = 
                loAm.getValueSessionFromAttribute("loggedPgmIntegrationUser");
            lsWhere += " AND USER_NAME = '"+lsUserName+"'";
        }
        else{
            lsWhere = getWhereClause();
        }
        //System.out.println(getQuery());
        setWhereClause(lsWhere);
        setOrderByClause("FEC_CREATION_DATE DESC");
        super.executeQueryForCollection(toQc, taParams, tiNumUserParams);
    }

}

