package mx.com.televisa.landamark.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 08 17:28:01 CDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntServicesCatVwViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntServicesCatVwViewImpl() {
    }
    @Override
    protected void executeQueryForCollection(Object toQc, 
                                             Object[] taParams, 
                                             int tiNumUserParams) {
        
        String lsWhere = " 1 = 1 ";
        lsWhere += " AND ATTRIBUTE1 IS NULL";
        //System.out.println(getQuery());
        setWhereClause(lsWhere);
        super.executeQueryForCollection(toQc, taParams, tiNumUserParams);
    }
    
}

