package mx.com.televisa.landamark.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 05 19:51:18 CST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntServiceBitacoraTabViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntServiceBitacoraTabViewImpl() {
    }
}

