package mx.com.televisa.landamark.model;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 08 17:28:01 CDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LmkIntServicesCatVwViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_LMKINTSERVICESCATVW = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdService,
        NomService,
        IndDescService,
        IndServiceWsdl,
        IndOrigin,
        IndDestiny,
        IndSystem,
        IndSynchronous,
        IndCronConfig,
        IndCronActive,
        IndCronExe,
        IndCronBegin,
        IndCronStop,
        IndShowParam,
        IndParameters,
        IndEstatus,
        AttributeCategory,
        Attribute1,
        Attribute2,
        Attribute3,
        Attribute4,
        Attribute5,
        Attribute6,
        Attribute7,
        Attribute8,
        Attribute9,
        Attribute10,
        Attribute11,
        Attribute12,
        Attribute13,
        Attribute14,
        Attribute15,
        FecCreationDate,
        NumCreatedBy,
        FecLastUpdateDate,
        NumLastUpdatedBy,
        NumLastUpdateLogin;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDSERVICE = AttributesEnum.IdService.index();
    public static final int NOMSERVICE = AttributesEnum.NomService.index();
    public static final int INDDESCSERVICE = AttributesEnum.IndDescService.index();
    public static final int INDSERVICEWSDL = AttributesEnum.IndServiceWsdl.index();
    public static final int INDORIGIN = AttributesEnum.IndOrigin.index();
    public static final int INDDESTINY = AttributesEnum.IndDestiny.index();
    public static final int INDSYSTEM = AttributesEnum.IndSystem.index();
    public static final int INDSYNCHRONOUS = AttributesEnum.IndSynchronous.index();
    public static final int INDCRONCONFIG = AttributesEnum.IndCronConfig.index();
    public static final int INDCRONACTIVE = AttributesEnum.IndCronActive.index();
    public static final int INDCRONEXE = AttributesEnum.IndCronExe.index();
    public static final int INDCRONBEGIN = AttributesEnum.IndCronBegin.index();
    public static final int INDCRONSTOP = AttributesEnum.IndCronStop.index();
    public static final int INDSHOWPARAM = AttributesEnum.IndShowParam.index();
    public static final int INDPARAMETERS = AttributesEnum.IndParameters.index();
    public static final int INDESTATUS = AttributesEnum.IndEstatus.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int FECCREATIONDATE = AttributesEnum.FecCreationDate.index();
    public static final int NUMCREATEDBY = AttributesEnum.NumCreatedBy.index();
    public static final int FECLASTUPDATEDATE = AttributesEnum.FecLastUpdateDate.index();
    public static final int NUMLASTUPDATEDBY = AttributesEnum.NumLastUpdatedBy.index();
    public static final int NUMLASTUPDATELOGIN = AttributesEnum.NumLastUpdateLogin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LmkIntServicesCatVwViewRowImpl() {
    }

    /**
     * Gets LmkIntServicesCatVw entity object.
     * @return the LmkIntServicesCatVw
     */
    public EntityImpl getLmkIntServicesCatVw() {
        return (EntityImpl) getEntity(ENTITY_LMKINTSERVICESCATVW);
    }

    /**
     * Gets the attribute value for ID_SERVICE using the alias name IdService.
     * @return the ID_SERVICE
     */
    public Integer getIdService() {
        return (Integer) getAttributeInternal(IDSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SERVICE using the alias name IdService.
     * @param value value to set the ID_SERVICE
     */
    public void setIdService(Integer value) {
        setAttributeInternal(IDSERVICE, value);
    }

    /**
     * Gets the attribute value for NOM_SERVICE using the alias name NomService.
     * @return the NOM_SERVICE
     */
    public String getNomService() {
        return (String) getAttributeInternal(NOMSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for NOM_SERVICE using the alias name NomService.
     * @param value value to set the NOM_SERVICE
     */
    public void setNomService(String value) {
        setAttributeInternal(NOMSERVICE, value);
    }

    /**
     * Gets the attribute value for IND_DESC_SERVICE using the alias name IndDescService.
     * @return the IND_DESC_SERVICE
     */
    public String getIndDescService() {
        return (String) getAttributeInternal(INDDESCSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_DESC_SERVICE using the alias name IndDescService.
     * @param value value to set the IND_DESC_SERVICE
     */
    public void setIndDescService(String value) {
        setAttributeInternal(INDDESCSERVICE, value);
    }

    /**
     * Gets the attribute value for IND_SERVICE_WSDL using the alias name IndServiceWsdl.
     * @return the IND_SERVICE_WSDL
     */
    public String getIndServiceWsdl() {
        return (String) getAttributeInternal(INDSERVICEWSDL);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SERVICE_WSDL using the alias name IndServiceWsdl.
     * @param value value to set the IND_SERVICE_WSDL
     */
    public void setIndServiceWsdl(String value) {
        setAttributeInternal(INDSERVICEWSDL, value);
    }

    /**
     * Gets the attribute value for IND_ORIGIN using the alias name IndOrigin.
     * @return the IND_ORIGIN
     */
    public String getIndOrigin() {
        return (String) getAttributeInternal(INDORIGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_ORIGIN using the alias name IndOrigin.
     * @param value value to set the IND_ORIGIN
     */
    public void setIndOrigin(String value) {
        setAttributeInternal(INDORIGIN, value);
    }

    /**
     * Gets the attribute value for IND_DESTINY using the alias name IndDestiny.
     * @return the IND_DESTINY
     */
    public String getIndDestiny() {
        return (String) getAttributeInternal(INDDESTINY);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_DESTINY using the alias name IndDestiny.
     * @param value value to set the IND_DESTINY
     */
    public void setIndDestiny(String value) {
        setAttributeInternal(INDDESTINY, value);
    }

    /**
     * Gets the attribute value for IND_SYSTEM using the alias name IndSystem.
     * @return the IND_SYSTEM
     */
    public String getIndSystem() {
        return (String) getAttributeInternal(INDSYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SYSTEM using the alias name IndSystem.
     * @param value value to set the IND_SYSTEM
     */
    public void setIndSystem(String value) {
        setAttributeInternal(INDSYSTEM, value);
    }

    /**
     * Gets the attribute value for IND_SYNCHRONOUS using the alias name IndSynchronous.
     * @return the IND_SYNCHRONOUS
     */
    public String getIndSynchronous() {
        return (String) getAttributeInternal(INDSYNCHRONOUS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SYNCHRONOUS using the alias name IndSynchronous.
     * @param value value to set the IND_SYNCHRONOUS
     */
    public void setIndSynchronous(String value) {
        setAttributeInternal(INDSYNCHRONOUS, value);
    }

    /**
     * Gets the attribute value for IND_CRON_CONFIG using the alias name IndCronConfig.
     * @return the IND_CRON_CONFIG
     */
    public String getIndCronConfig() {
        return (String) getAttributeInternal(INDCRONCONFIG);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_CONFIG using the alias name IndCronConfig.
     * @param value value to set the IND_CRON_CONFIG
     */
    public void setIndCronConfig(String value) {
        setAttributeInternal(INDCRONCONFIG, value);
    }

    /**
     * Gets the attribute value for IND_CRON_ACTIVE using the alias name IndCronActive.
     * @return the IND_CRON_ACTIVE
     */
    public String getIndCronActive() {
        return (String) getAttributeInternal(INDCRONACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_ACTIVE using the alias name IndCronActive.
     * @param value value to set the IND_CRON_ACTIVE
     */
    public void setIndCronActive(String value) {
        setAttributeInternal(INDCRONACTIVE, value);
    }

    /**
     * Gets the attribute value for IND_CRON_EXE using the alias name IndCronExe.
     * @return the IND_CRON_EXE
     */
    public String getIndCronExe() {
        return (String) getAttributeInternal(INDCRONEXE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_EXE using the alias name IndCronExe.
     * @param value value to set the IND_CRON_EXE
     */
    public void setIndCronExe(String value) {
        setAttributeInternal(INDCRONEXE, value);
    }

    /**
     * Gets the attribute value for IND_CRON_BEGIN using the alias name IndCronBegin.
     * @return the IND_CRON_BEGIN
     */
    public String getIndCronBegin() {
        return (String) getAttributeInternal(INDCRONBEGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_BEGIN using the alias name IndCronBegin.
     * @param value value to set the IND_CRON_BEGIN
     */
    public void setIndCronBegin(String value) {
        setAttributeInternal(INDCRONBEGIN, value);
    }

    /**
     * Gets the attribute value for IND_CRON_STOP using the alias name IndCronStop.
     * @return the IND_CRON_STOP
     */
    public String getIndCronStop() {
        return (String) getAttributeInternal(INDCRONSTOP);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_CRON_STOP using the alias name IndCronStop.
     * @param value value to set the IND_CRON_STOP
     */
    public void setIndCronStop(String value) {
        setAttributeInternal(INDCRONSTOP, value);
    }

    /**
     * Gets the attribute value for IND_SHOW_PARAM using the alias name IndShowParam.
     * @return the IND_SHOW_PARAM
     */
    public String getIndShowParam() {
        return (String) getAttributeInternal(INDSHOWPARAM);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SHOW_PARAM using the alias name IndShowParam.
     * @param value value to set the IND_SHOW_PARAM
     */
    public void setIndShowParam(String value) {
        setAttributeInternal(INDSHOWPARAM, value);
    }

    /**
     * Gets the attribute value for IND_PARAMETERS using the alias name IndParameters.
     * @return the IND_PARAMETERS
     */
    public String getIndParameters() {
        return (String) getAttributeInternal(INDPARAMETERS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_PARAMETERS using the alias name IndParameters.
     * @param value value to set the IND_PARAMETERS
     */
    public void setIndParameters(String value) {
        setAttributeInternal(INDPARAMETERS, value);
    }

    /**
     * Gets the attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @return the IND_ESTATUS
     */
    public String getIndEstatus() {
        return (String) getAttributeInternal(INDESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @param value value to set the IND_ESTATUS
     */
    public void setIndEstatus(String value) {
        setAttributeInternal(INDESTATUS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @return the FEC_CREATION_DATE
     */
    public Timestamp getFecCreationDate() {
        return (Timestamp) getAttributeInternal(FECCREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @param value value to set the FEC_CREATION_DATE
     */
    public void setFecCreationDate(Timestamp value) {
        setAttributeInternal(FECCREATIONDATE, value);
    }

    /**
     * Gets the attribute value for NUM_CREATED_BY using the alias name NumCreatedBy.
     * @return the NUM_CREATED_BY
     */
    public Integer getNumCreatedBy() {
        return (Integer) getAttributeInternal(NUMCREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_CREATED_BY using the alias name NumCreatedBy.
     * @param value value to set the NUM_CREATED_BY
     */
    public void setNumCreatedBy(Integer value) {
        setAttributeInternal(NUMCREATEDBY, value);
    }

    /**
     * Gets the attribute value for FEC_LAST_UPDATE_DATE using the alias name FecLastUpdateDate.
     * @return the FEC_LAST_UPDATE_DATE
     */
    public Timestamp getFecLastUpdateDate() {
        return (Timestamp) getAttributeInternal(FECLASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_LAST_UPDATE_DATE using the alias name FecLastUpdateDate.
     * @param value value to set the FEC_LAST_UPDATE_DATE
     */
    public void setFecLastUpdateDate(Timestamp value) {
        setAttributeInternal(FECLASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for NUM_LAST_UPDATED_BY using the alias name NumLastUpdatedBy.
     * @return the NUM_LAST_UPDATED_BY
     */
    public Integer getNumLastUpdatedBy() {
        return (Integer) getAttributeInternal(NUMLASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_LAST_UPDATED_BY using the alias name NumLastUpdatedBy.
     * @param value value to set the NUM_LAST_UPDATED_BY
     */
    public void setNumLastUpdatedBy(Integer value) {
        setAttributeInternal(NUMLASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for NUM_LAST_UPDATE_LOGIN using the alias name NumLastUpdateLogin.
     * @return the NUM_LAST_UPDATE_LOGIN
     */
    public Integer getNumLastUpdateLogin() {
        return (Integer) getAttributeInternal(NUMLASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM_LAST_UPDATE_LOGIN using the alias name NumLastUpdateLogin.
     * @param value value to set the NUM_LAST_UPDATE_LOGIN
     */
    public void setNumLastUpdateLogin(Integer value) {
        setAttributeInternal(NUMLASTUPDATELOGIN, value);
    }
}

